Run("C:\Users\Administrator\Documents\EnglishEdge - Demo V2\EnglishEdge.exe")
Sleep(2000)
WinActivate("Open File - Security Warning")
ControlFocus("Open File - Security Warning","","Button1")
ControlClick("Open File - Security Warning","","Button1")
Sleep(600000)